language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer update --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-text
